language: dart
os:
  - linux
sudo: false
dart:
  - 2.7.0
script:
  - pub get
  - pub run test test/
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
