language: dart
os:
  - linux
sudo: false
dart:
  - 2.12.0
script:
  - pub get
  - pub global activate test_coverage
  - pub run test test/
  - test_coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
