include: package:lint/analysis_options.yaml
linter:
  rules:
    parameter_assignments: true
    prefer_function_declarations_over_variables: false
    ambiguous_extension_member_access: false
analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
