include: package:lint/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: true
    parameter_assignments: true
    prefer_function_declarations_over_variables: false
    ambiguous_extension_member_access: false
    require_trailing_commas: false
analyzer:
  exclude:
    - example/**
    - pubspec.yaml

  errors:
    missing_required_param: error
    parameter_assignments: error
