name: verify
description: Validations made simple. An extension based validation DSL.
version: 0.1.0
homepage: https://github.com/DanielCardonaRojas/verify

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.0.0
  dartz: ^0.8.6
  meta: ^1.1.8

dev_dependencies:
  lint: ^1.0.0
  test: ^1.14.2
