name: verify
description: Validations made simple. An extension based validation DSL.
version: 1.1.0
homepage: https://github.com/DanielCardonaRojas/verify

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  dartz: ^0.8.6
  meta: ^1.1.8

dev_dependencies:
  equatable: ^1.0.0
  lint: ^1.0.0
  test_coverage: ^0.4.1
  test: ^1.14.2
