name: verify
version: 2.0.1
homepage: https://github.com/DanielCardonaRojas/verify
description: Validations made simple. An extension based state validation DSL.
author: Daniel Cardona <d.cardona.rojas@gmail.com>

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  dartz: ^0.10.1

dev_dependencies:
  equatable: ^2.0.0
  lint: ^1.5.3
  test: ^1.24.7
