name: verify
description: Validations made simple. An extension based validation DSL.
version: 2.0.0-nullsafety.1
homepage: https://github.com/DanielCardonaRojas/verify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dartz: ">=0.10.0-nullsafety.2 <1.0.0"

dev_dependencies:
  equatable: ^2.0.0
  lint: ^1.5.3
  test: ^1.16.7
  test_coverage: ^0.5.0
